### ISSUE TITLE
AWS Client spams debug logs when using secretsManager

### ISSUE THREAD

**Issue by jahed** [unruly/java-config-fallback#8]
AWS clients try to resolve configuration from multiple places. As it does this, it logs DEBUG messages when it can't find what it needs as it traverses.

The issue is that if I set up a Configuration on a `static` scope, it potentially creates the AWS Client and starts debug logging before my application can configure debug logs (see end of this post). Here's the current setup:

```java
private static ConfigurationSource config = Configuration.secretsManager("my/key", "eu-west-1");

public static Credentials get() {
    return new Credentials(config.get("username"), config.get("access_key"));
}
```

It would be nice if `Configuration.secretsManager` only created the client when it requests a secret and disposes of it after since it won't ever be used again (as the response is cached). This would remove side effects from the constructor and resolve the debug logging issue.

What do you think? I can send a PR for this if there aren't any disagreements.

My current workaround is to lazy initialise the entire Configuration:
```java
    private static Credentials CREDENTIALS;
    public static Credentials get() {
        if (CREDENTIALS == null) {
            ConfigurationSource source = Configuration.secretsManager("my/key", "eu-west-1");
            CREDENTIALS = new Credentials(source.get("username"), source.get("access_key"));
        }
        return CREDENTIALS;
    }
```

<details>
<summary>Click here to see log output</summary>
```
com.amazonaws.SdkClientException: Unable to load Client Side Monitoring configurations from environment variables!
	at com.amazonaws.monitoring.EnvironmentVariableCsmConfigurationProvider.getConfiguration(EnvironmentVariableCsmConfigurationProvider.java:42)
	at com.amazonaws.monitoring.CsmConfigurationProviderChain.getConfiguration(CsmConfigurationProviderChain.java:45)
	at com.amazonaws.AmazonWebServiceClient.getCsmConfiguration(AmazonWebServiceClient.java:1048)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:195)
	at com.amazonaws.services.secretsmanager.AWSSecretsManagerClient.<init>(AWSSecretsManagerClient.java:194)
	at com.amazonaws.services.secretsmanager.AWSSecretsManagerClientBuilder.build(AWSSecretsManagerClientBuilder.java:61)
	at com.amazonaws.services.secretsmanager.AWSSecretsManagerClientBuilder.build(AWSSecretsManagerClientBuilder.java:27)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at co.unruly.config.SecretsManager.setupClient(SecretsManager.java:57)
	at co.unruly.config.SecretsManager.<init>(SecretsManager.java:26)
	at co.unruly.config.Configuration.secretsManager(Configuration.java:73)
	at com.unrulymedia.native_acceptance_tests.configuration.BrowserStackCredentials.<clinit>(BrowserStackCredentials.java:24)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.junit.extensions.cpsuite.ClasspathClassesFinder.gatherClasses(ClasspathClassesFinder.java:87)
	at org.junit.extensions.cpsuite.ClasspathClassesFinder.gatherClassesInRoot(ClasspathClassesFinder.java:67)
	at org.junit.extensions.cpsuite.ClasspathClassesFinder.findClassesInRoots(ClasspathClassesFinder.java:50)
	at org.junit.extensions.cpsuite.ClasspathClassesFinder.findClassesInClasspath(ClasspathClassesFinder.java:44)
	at org.junit.extensions.cpsuite.ClasspathClassesFinder.find(ClasspathClassesFinder.java:33)
	at org.junit.extensions.cpsuite.ClasspathSuite.getSortedTestclasses(ClasspathSuite.java:127)
	at org.junit.extensions.cpsuite.ClasspathSuite.<init>(ClasspathSuite.java:117)
	at org.junit.extensions.cpsuite.ClasspathSuite.<init>(ClasspathSuite.java:110)
	at com.unrulymedia.native_acceptance_tests.runners.ClasspathCategorySuite.<init>(ClasspathCategorySuite.java:21)
	at com.unrulymedia.native_acceptance_tests.runners.ParallelClasspathCategorySuite.<init>(ParallelClasspathCategorySuite.java:10)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:107)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87)
	at org.junit.runners.Suite.<init>(Suite.java:102)
	at org.junit.runners.Suite.<init>(Suite.java:70)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:107)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
10:45:07.380 [main] DEBUG com.amazonaws.monitoring.CsmConfigurationProviderChain - Unable to load configuration from com.amazonaws.monitoring.SystemPropertyCsmConfigurationProvider@55b53d44
com.amazonaws.SdkClientException: Unable to load Client Side Monitoring configurations from system properties variables!
	at com.amazonaws.monitoring.SystemPropertyCsmConfigurationProvider.getConfiguration(SystemPropertyCsmConfigurationProvider.java:40)
	at com.amazonaws.monitoring.CsmConfigurationProviderChain.getConfiguration(CsmConfigurationProviderChain.java:45)
	at com.amazonaws.AmazonWebServiceClient.getCsmConfiguration(AmazonWebServiceClient.java:1048)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:195)
	at com.amazonaws.services.secretsmanager.AWSSecretsManagerClient.<init>(AWSSecretsManagerClient.java:194)
	at com.amazonaws.services.secretsmanager.AWSSecretsManagerClientBuilder.build(AWSSecretsManagerClientBuilder.java:61)
	at com.amazonaws.services.secretsmanager.AWSSecretsManagerClientBuilder.build(AWSSecretsManagerClientBuilder.java:27)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at co.unruly.config.SecretsManager.setupClient(SecretsManager.java:57)
	at co.unruly.config.SecretsManager.<init>(SecretsManager.java:26)
	at co.unruly.config.Configuration.secretsManager(Configuration.java:73)
	at com.unrulymedia.native_acceptance_tests.configuration.BrowserStackCredentials.<clinit>(BrowserStackCredentials.java:24)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.junit.extensions.cpsuite.ClasspathClassesFinder.gatherClasses(ClasspathClassesFinder.java:87)
	at org.junit.extensions.cpsuite.ClasspathClassesFinder.gatherClassesInRoot(ClasspathClassesFinder.java:67)
	at org.junit.extensions.cpsuite.ClasspathClassesFinder.findClassesInRoots(ClasspathClassesFinder.java:50)
	at org.junit.extensions.cpsuite.ClasspathClassesFinder.findClassesInClasspath(ClasspathClassesFinder.java:44)
	at org.junit.extensions.cpsuite.ClasspathClassesFinder.find(ClasspathClassesFinder.java:33)
	at org.junit.extensions.cpsuite.ClasspathSuite.getSortedTestclasses(ClasspathSuite.java:127)
	at org.junit.extensions.cpsuite.ClasspathSuite.<init>(ClasspathSuite.java:117)
	at org.junit.extensions.cpsuite.ClasspathSuite.<init>(ClasspathSuite.java:110)
	at com.unrulymedia.native_acceptance_tests.runners.ClasspathCategorySuite.<init>(ClasspathCategorySuite.java:21)
	at com.unrulymedia.native_acceptance_tests.runners.ParallelClasspathCategorySuite.<init>(ParallelClasspathCategorySuite.java:10)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:107)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87)
	at org.junit.runners.Suite.<init>(Suite.java:102)
	at org.junit.runners.Suite.<init>(Suite.java:70)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:107)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
10:45:07.385 [main] DEBUG com.amazonaws.monitoring.CsmConfigurationProviderChain - Unable to load configuration from com.amazonaws.monitoring.ProfileCsmConfigurationProvider@19d481b
com.amazonaws.SdkClientException: The 'default' profile does not define all the required properties!
	at com.amazonaws.monitoring.ProfileCsmConfigurationProvider.getConfiguration(ProfileCsmConfigurationProvider.java:97)
	at com.amazonaws.monitoring.CsmConfigurationProviderChain.getConfiguration(CsmConfigurationProviderChain.java:45)
	at com.amazonaws.AmazonWebServiceClient.getCsmConfiguration(AmazonWebServiceClient.java:1048)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:195)
	at com.amazonaws.services.secretsmanager.AWSSecretsManagerClient.<init>(AWSSecretsManagerClient.java:194)
	at com.amazonaws.services.secretsmanager.AWSSecretsManagerClientBuilder.build(AWSSecretsManagerClientBuilder.java:61)
	at com.amazonaws.services.secretsmanager.AWSSecretsManagerClientBuilder.build(AWSSecretsManagerClientBuilder.java:27)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at co.unruly.config.SecretsManager.setupClient(SecretsManager.java:57)
	at co.unruly.config.SecretsManager.<init>(SecretsManager.java:26)
	at co.unruly.config.Configuration.secretsManager(Configuration.java:73)
	at com.unrulymedia.native_acceptance_tests.configuration.BrowserStackCredentials.<clinit>(BrowserStackCredentials.java:24)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.junit.extensions.cpsuite.ClasspathClassesFinder.gatherClasses(ClasspathClassesFinder.java:87)
	at org.junit.extensions.cpsuite.ClasspathClassesFinder.gatherClassesInRoot(ClasspathClassesFinder.java:67)
	at org.junit.extensions.cpsuite.ClasspathClassesFinder.findClassesInRoots(ClasspathClassesFinder.java:50)
	at org.junit.extensions.cpsuite.ClasspathClassesFinder.findClassesInClasspath(ClasspathClassesFinder.java:44)
	at org.junit.extensions.cpsuite.ClasspathClassesFinder.find(ClasspathClassesFinder.java:33)
	at org.junit.extensions.cpsuite.ClasspathSuite.getSortedTestclasses(ClasspathSuite.java:127)
	at org.junit.extensions.cpsuite.ClasspathSuite.<init>(ClasspathSuite.java:117)
	at org.junit.extensions.cpsuite.ClasspathSuite.<init>(ClasspathSuite.java:110)
	at com.unrulymedia.native_acceptance_tests.runners.ClasspathCategorySuite.<init>(ClasspathCategorySuite.java:21)
	at com.unrulymedia.native_acceptance_tests.runners.ParallelClasspathCategorySuite.<init>(ParallelClasspathCategorySuite.java:10)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:107)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87)
	at org.junit.runners.Suite.<init>(Suite.java:102)
	at org.junit.runners.Suite.<init>(Suite.java:70)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:107)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```
</details>

**Comment by mrwilson** [comment]
This sounds like a useful change - it's a good idea to keep core ConfigurationSources that talk to external resources as lazy as possible.
